services:
  # Node.js Express Application
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: express-hello-world
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    networks:
      - app-network
    # Removed volumes for production - uncomment for development
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # SSL certificates (if using HTTPS)
      # - ./certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - app

  # Development version with hot reload
  app-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: express-hello-world-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - development

networks:
  app-network:
    driver: bridge

# Optional: Add volumes for data persistence
# volumes:
#   app-data:
